version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: gubsocosta/node-fs3.0-desafio-docker
    container_name: app
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"