version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: gubsocosta/node-fs3.0-desafio-docker:prod
    container_name: app
    tty: true
    ports:
      - "3000:3000"