FROM node:lts-alpine as builder
WORKDIR /home/node/app
COPY package*.json .
RUN npm install

FROM node:lts-alpine as runner
WORKDIR /home/node/app
COPY --from=builder /home/node/app/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]